spring.application.name=checkinplay
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=myapp
spring.datasource.password=myapp
spring.datasource.url=jdbc:postgresql://localhost:5432/myapp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true